baseURL = 'https://www.windtunel.cn/COM-GHV-beyond/'
languageCode = 'en-us'
title = 'Control-Oriented-Model of Generic Hypersonic Vehicle and beyond'
theme = "hugo-book"

[params]
  gitsite = 'https://github.com/qchen-fdii-cardc/COM-GHV-beyond'
  maxImgSize = 400

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true  # Enables raw HTML in markdown

  [markup.goldmark.parser]
    [markup.goldmark.parser.attribute]
      block = true
      title = true
  [markup.goldmark.extensions]
    [markup.goldmark.extensions.passthrough]
      enable = true
      [markup.goldmark.extensions.passthrough.delimiters]
        block = [['\[', '\]'], ['$$', '$$']]
        inline = [['\(', '\)'], ['$', '$']]

